name: Triffic Blog
description: Triffic Personal WebBlog
baseurl: ''

url: "http://triffic.cn"

paginate: 10

# highlight code
pygments: true

# 
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
