# Site settings
title: "Spectrum-o"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: ellenleeqr@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  一个野生设计师
  <br/>ellenleeqr@yahoo.com
    <br/>微信公众号：Spectrum-d
    <br/>哔哩哔哩：Spectrum-o

url: "http://pandaqr.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

paginate: 8
paginate_path: "blog/page:num"
gems: [jekyll-paginate]

twitter_username: ellenliqr
github_username:  pandaqr


# Build settings
markdown: kramdown
