name: Notebook
description: Pain is inevitable, Suffering is optional.
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
pygments: true
logo: false
paginate: 15


# baseurl: http://rulerstorm.github.io

# Details for the RSS feed generator
url:            'http://pandaqr.github.io'
author:         'Ellen'
